apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: default 
data:
  alert-rule.yml: |
    groups:
      - name: Kafka Alerts
        rules:
          - alert: KafkaConsumerLagHigh
            expr: kafka_consumergroup_lag > 100
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Kafka consumer lag is too high"
              description: "Consumer lag is {{ $value }} messages for group {{ $labels.group }}."

      - name: Redis Alerts
        rules:
          - alert: RedisMemoryHigh
            expr: redis_memory_used_bytes > 500000000
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Redis memory usage is high"
              description: "Redis is using {{ $value }} bytes of memory."

      - name: Kubernetes Alerts
        rules:
          - alert: PodMemoryUsageHigh
            expr: container_memory_working_set_bytes / container_spec_memory_limit_bytes > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Pod memory usage is high"
              description: "Pod {{ $labels.pod }} is using {{ $value }} of its memory limit."

          - alert: PodRestarting
            expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
            for: 10m
            labels:
              severity: critical
            annotations:
              summary: "Pod is restarting frequently"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently."
